### PR TITLE
Improve Form Design #3 resolved

### LINKED ISSUE #3: Improve Form Design
Screenshot (53)

Make the Form more attractive.

Try to do something with `white-background` in inputs

### PR DESCRIPTION
**Pull request by rohit-raje-786**
Improve the form design and added gitignore files so as to avoid uploading the node_modules on github 

fixed #3 .

Before:
Screenshot 2022-10-06 at 2 36 38 PM

After:
Screenshot 2022-10-06 at 2 31 41 PM

Please review it @RamGoel.

### CODE REVIEW

**Comment by RamGoel** [comment]
@rohit-raje-786 It looks good but the white button doesn't seems good plus can you make the placeholders little smaller and decrease the opacity of them. 

Note : Only Placeholders, not actual text.

If you find any issues,you can ask it here.

**Comment by rohit-raje-786** [comment]
which color do you want for the submit button?

**Comment by RamGoel** [comment]
Try out which looks good.

**Comment by rohit-raje-786** [comment]
Screenshot 2022-10-06 at 2 58 54 PM

Done @RamGoel

**Comment by rohit-raje-786** [comment]
@RamGoel could you please review and merge it?

**Comment by rohit-raje-786** [comment]
@RamGoel could you please look into this 👆?

**Comment by RamGoel** [comment]
Hi @rohit-raje-786  sorry for responding late , the changes looks good but the changes in `package-lock.json` looks unneccessary as this task doesn't need any package changes. so revert the changes in `package-lock.json` and commit the changes

**Comment by rohit-raje-786** [comment]
@RamGoel it is done ✅

**Comment by rohit-raje-786** [comment]
@RamGoel hey the  final changes have been done could you please review it

**Comment by RamGoel** [comment]
GTG 🚀.  Thanks for Contributing.

**Comment by rohit-raje-786** [comment]
@RamGoel could please add a label of hactoberfest-accepted

**Pull request merged**
