### PR TITLE
Design: Improve Article Card List Design

### LINKED ISSUE #1: Improve Article Card List Design
Screenshot (52)

Improve the Design of Cards

### PR DESCRIPTION
**Pull request by tanishk-23**
Cards
fixes #1

### CODE REVIEW

**Comment by RamGoel** [comment]
Looks good @tanishk-23 , 

- [ ] Remove the shadow on tags.
- [ ] Make tags `font-color:white`.
- [ ] Add a divider b/w card-head and card-content.

Do these changes and we're good to go.

**Comment by tanishk-23** [comment]
@RamGoel I have implemented all your suggested changes. You can review the PR now.

**Comment by RamGoel** [comment]
@tanishk-23 please share the preview.

**Comment by tanishk-23** [comment]
Here's the preview after the changes
Lekhak

**Comment by RamGoel** [comment]
Can you share the shot of the articles in the previous image shared by you.

**Comment by RamGoel** [comment]
> Cards fixes #1

This one.

**Comment by tanishk-23** [comment]
This is the Screenshot I shared previously.
IMG_20221008_234419

**Comment by RamGoel** [comment]
Now Take a Screenshot of Article page and Send

**Comment by tanishk-23** [comment]
IMG_20221008_235944

**Comment by RamGoel** [comment]
Okay, GTG. Thanks 🚀

**Pull request merged**
