### PR TITLE
'added help.ejs , help.css and route in app.js'

### PR DESCRIPTION
**Pull request by KGoutham7214**
added the route to app.js and looking forward to work for more issues in repo

### CODE REVIEW

**Comment by RamGoel** [comment]
Hi @KGoutham7214 , I think you have pushed some unneccessary changes in `package-lock.json` which is of about 2500 lines. Please fix it.

BTW thanks for the amazing work. It'll be great if you can attach a preview screenshot of it.

**Comment by KGoutham7214** [comment]
sure i'll work on it in not time , thanks for the reply

**Comment by KGoutham7214** [comment]
i just did the ( npm init )again using latest version where name can't be capitals so i had to change it to (lekhak-hactober)


image

**Comment by KGoutham7214** [comment]
do check the lastest commit i have solved the issue with package-lock.json file and also added the titles to the page

**Comment by KGoutham7214** [comment]
more preview images with titleshome

help

**Comment by KGoutham7214** [comment]
do leave a reply if any changes needed

**Comment by RamGoel** [comment]
Looks good, but can we have any image in left side and the form on right side plus the font inside the text-inputs should sync with website font.

**Comment by RamGoel** [comment]
Hi @KGoutham7214 @fosa-ij Can you guys work together on this issue and make a help page which has FAQ on the left and form on the right side.

**Comment by KGoutham7214** [comment]
Sure will start working on it

**Pull request closed without merging**
