### PR TITLE
updated titles of every page

### PR DESCRIPTION
**Pull request by heyvats21**

### CODE REVIEW

**Comment by RamGoel** [comment]
Hi @heyvats21 thanks for opening a PR. The page titles should be relevant according to pages.

Like Add New Article or Add Article for Add.js. Please fix them.


Thanks :)

**Comment by RamGoel** [comment]
Thanks for contributing, can you merge all these commits into single commit.

**Comment by heyvats21** [comment]
its in a single commit .you can merge it into main branch.

**Comment by RamGoel** [comment]
Combine all the three commits into one commit.

**Comment by heyvats21** [comment]
is it okk now??

**Comment by heyvats21** [comment]
@RamGoel  can you see this

**Comment by RamGoel** [comment]
Yes, GTG. Thanks for Contributing.

**Pull request merged**
